# Generated by Django 5.0 on 2024-04-25 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='address_line1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address_line2',
        ),
    ]
