# Generated by Django 5.0 on 2024-04-28 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_rename_crated_at_category_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='crated_at',
            new_name='created_at',
        ),
    ]
